use super::types::*;

pub const ACCOUNT_FIELDS: &[FieldDef] = &[
    FieldDef {
        name: "id",
        column: "id",
        scalar: Some(ScalarType::Id),
        is_primary_key: true,
        is_filterable: true,
        is_sortable: true,
        is_writable: false,
        has_default: true,
        relation: None,
    },
    FieldDef {
        name: "orgId",
        column: "org_id",
        scalar: Some(ScalarType::String),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "createdAt",
        column: "created_at",
        scalar: Some(ScalarType::DateTime),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: true,
        is_writable: false,
        has_default: true,
        relation: None,
    },
    FieldDef {
        name: "updatedAt",
        column: "updated_at",
        scalar: Some(ScalarType::DateTime),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: true,
        is_writable: false,
        has_default: true,
        relation: None,
    },
    FieldDef {
        name: "name",
        column: "name",
        scalar: Some(ScalarType::String),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: true,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "industry",
        column: "industry",
        scalar: Some(ScalarType::String),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "website",
        column: "website",
        scalar: Some(ScalarType::String),
        is_primary_key: false,
        is_filterable: false,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "phone",
        column: "phone",
        scalar: Some(ScalarType::String),
        is_primary_key: false,
        is_filterable: false,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
];

pub const ACCOUNT_MODEL: &ModelDef = &ModelDef {
    name: "Account",
    table: "accounts",
    fields: ACCOUNT_FIELDS,
};
