use super::types::*;

pub const CONTACT_FIELDS: &[FieldDef] = &[
    FieldDef {
        name: "id",
        column: "id",
        scalar: Some(ScalarType::Id),
        is_primary_key: true,
        is_filterable: true,
        is_sortable: true,
        is_writable: false,
        has_default: true,
        relation: None,
    },
    FieldDef {
        name: "orgId",
        column: "org_id",
        scalar: Some(ScalarType::String),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "accountId",
        column: "account_id",
        scalar: Some(ScalarType::Id),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "createdAt",
        column: "created_at",
        scalar: Some(ScalarType::DateTime),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: true,
        is_writable: false,
        has_default: true,
        relation: None,
    },
    FieldDef {
        name: "updatedAt",
        column: "updated_at",
        scalar: Some(ScalarType::DateTime),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: true,
        is_writable: false,
        has_default: true,
        relation: None,
    },
    FieldDef {
        name: "firstName",
        column: "first_name",
        scalar: Some(ScalarType::String),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: true,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "lastName",
        column: "last_name",
        scalar: Some(ScalarType::String),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: true,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "email",
        column: "email",
        scalar: Some(ScalarType::String),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "phone",
        column: "phone",
        scalar: Some(ScalarType::String),
        is_primary_key: false,
        is_filterable: false,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
];

pub const CONTACT_MODEL: &ModelDef = &ModelDef {
    name: "Contact",
    table: "contacts",
    fields: CONTACT_FIELDS,
};
