use super::types::*;

pub const OPPORTUNITY_FIELDS: &[FieldDef] = &[
    FieldDef {
        name: "id",
        column: "id",
        scalar: Some(ScalarType::Id),
        is_primary_key: true,
        is_filterable: true,
        is_sortable: true,
        is_writable: false,
        has_default: True,
        relation: None,
    },
    FieldDef {
        name: "orgId",
        column: "org_id",
        scalar: Some(ScalarType::String),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "accountId",
        column: "account_id",
        scalar: Some(ScalarType::Id),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "contactId",
        column: "contact_id",
        scalar: Some(ScalarType::Id),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "ownerId",
        column: "owner_id",
        scalar: Some(ScalarType::Id),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "name",
        column: "name",
        scalar: Some(ScalarType::String),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: true,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "amount",
        column: "amount",
        scalar: Some(ScalarType::Float),
        is_primary_key: false,
        is_filterable: false,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "currency",
        column: "currency",
        scalar: Some(ScalarType::String),
        is_primary_key: false,
        is_filterable: false,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "stage",
        column: "stage",
        scalar: Some(ScalarType::String),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "probability",
        column: "probability",
        scalar: Some(ScalarType::Int),
        is_primary_key: false,
        is_filterable: false,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "closeDate",
        column: "close_date",
        scalar: Some(ScalarType::String),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: true,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "source",
        column: "source",
        scalar: Some(ScalarType::String),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "description",
        column: "description",
        scalar: Some(ScalarType::String),
        is_primary_key: false,
        is_filterable: false,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "createdAt",
        column: "created_at",
        scalar: Some(ScalarType::DateTime),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: true,
        is_writable: false,
        has_default: True,
        relation: None,
    },
    FieldDef {
        name: "updatedAt",
        column: "updated_at",
        scalar: Some(ScalarType::DateTime),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: true,
        is_writable: false,
        has_default: True,
        relation: None,
    },
];

pub const OPPORTUNITY_MODEL: &ModelDef = &ModelDef {
    name: "Opportunity",
    table: "opportunities",
    fields: OPPORTUNITY_FIELDS,
};
