use super::types::*;

pub const SOCIAL_EVENT_FIELDS: &[FieldDef] = &[
    FieldDef {
        name: "id",
        column: "id",
        scalar: Some(ScalarType::Id),
        is_primary_key: true,
        is_filterable: true,
        is_sortable: true,
        is_writable: false,
        has_default: true,
        relation: None,
    },
    FieldDef {
        name: "orgId",
        column: "org_id",
        scalar: Some(ScalarType::String),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "platform",
        column: "platform",
        scalar: Some(ScalarType::String),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "channel",
        column: "channel",
        scalar: Some(ScalarType::String),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "verb",
        column: "verb",
        scalar: Some(ScalarType::String),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "direction",
        column: "direction",
        scalar: Some(ScalarType::String),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "text",
        column: "text",
        scalar: Some(ScalarType::String),
        is_primary_key: false,
        is_filterable: false,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "sentiment",
        column: "sentiment",
        scalar: Some(ScalarType::Float),
        is_primary_key: false,
        is_filterable: false,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "occurredAt",
        column: "occurred_at",
        scalar: Some(ScalarType::DateTime),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: true,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "accountId",
        column: "account_id",
        scalar: Some(ScalarType::Id),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "contactId",
        column: "contact_id",
        scalar: Some(ScalarType::Id),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "ticketId",
        column: "ticket_id",
        scalar: Some(ScalarType::Id),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "rawPayload",
        column: "raw_payload",
        scalar: Some(ScalarType::Json),
        is_primary_key: false,
        is_filterable: false,
        is_sortable: false,
        is_writable: true,
        has_default: false,
        relation: None,
    },
    FieldDef {
        name: "createdAt",
        column: "created_at",
        scalar: Some(ScalarType::DateTime),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: true,
        is_writable: false,
        has_default: true,
        relation: None,
    },
    FieldDef {
        name: "updatedAt",
        column: "updated_at",
        scalar: Some(ScalarType::DateTime),
        is_primary_key: false,
        is_filterable: true,
        is_sortable: true,
        is_writable: false,
        has_default: true,
        relation: None,
    },
];

pub const SOCIAL_EVENT_MODEL: &ModelDef = &ModelDef {
    name: "SocialEvent",
    table: "social_events",
    fields: SOCIAL_EVENT_FIELDS,
};
